### ISSUE TITLE
Translate Loans SCORE into Java

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-java-contracts#13]
Use the continuous rewards branch to translate Loans into Java

https://github.com/balancednetwork/balanced-contracts/tree/continuous-integration/core_contracts/loans

**Comment by AntonAndell** [comment]
Working on rewriting the LoansContract I can't really figure out why we want the current one translated. Feel like i am copying a lot of really unneded and "complicated" code. With this rewrite we have space for so many improvements. 

But the biggest being is the resdesign of contract in regards to Continous rewards which removes a lot of complexity, this should also make the data migration easier i reckon.  Getting rid of user history from the contract would make is so much nicer to work with.

Wouldn't it be cleaner to have the continuous rewards migration be the transition to java?

**Comment by BennyOptions** [comment]
Hey @AntonAndell - from my understanding, the reason all this code needs to be copied over is based on the planned/tested migration process. It is possible a more efficient process exists, which I'm sure people would be open to, but the plan is to:

1.) Do an update where continuous rewards is not active, but deployed on main net
2.) Have a set date where the contracts migrate from non-continuous to continuous rewards
3.) Activate continuous rewards at the aforementioned date

Pretty much, all the testing was done in a process where there is a brief period of time between the actual upgrade of the contract and the actual activation of continuous rewards. If any changes are made to this process, there would need to be a lot of new testing done as well.

@gedanziger @dbrehmer @nightowl121 feel free to elaborate if I'm missing something or misspoke.

**Comment by nightowl121** [comment]
Above was our plan with python contracts where we could update our contracts, wait for approval and set the live date according to our ease. 

What we could day with Java contracts is to do the update Just In Time when it's required. We can discuss more about this. We need to be precise with the update time, that could be one of the issue here.

**Comment by BennyOptions** [comment]
Personally, I would prefer to stick to the well-tested plan, even if it means extra work at this point. Open to suggestions/thoughts tho. @AntonAndell please continue migrating to Java, but if possible, perhaps save the portion of the migration work related to this discussion in case an equally-safe solution is found through this discussion

**Comment by AntonAndell** [comment]
Yeah the plan is still to do a full translation with all the features as of now, will probably have a draft of all functionality in place this week, however probably very buggy since there is a lot of data structures that is not that straightforward to translate. 

But when deploying java we can no longer Update contracts (I think). Thus we will probably have some functions in new contracts that  migrates data from the old and shuts it down. So if we do not do the continuous rewards migration directly when  we launch java we will have to do 2 data migrations. 
I don't know the plan on how to do this migration but the migration seems like a perfect time to reduce the amount of data a contract holds.

**Comment by BennyOptions** [comment]
For what it's worth, upgrading contracts is still possible on Java, but I'll let the other folks respond if there's any other thoughts on the matter.
