### ISSUE TITLE
Request to add an external readonly method "getPoolTotalAt" on DEX contract 

### ISSUE THREAD

**Issue by habbas33** [balancednetwork/balanced-java-contracts#75]
Our team is working on foligator- an analytics tool for balanced.
Balanced Dex score has a method "getPoolTotal(self, _id: int, _token: Address)" which returns the current pool total for base or quote. 
We want something like getPoolTotalAt(self, _id: int, _token: Address, day: int) on DEX contract. It will improve accuracy of our results.

**Comment by nightowl121** [comment]
Hey @habbas33, it would be better for you to use new feature in ICON blockchain where you can query read only methods using block height.

Or use this method to use the time
https://tracker.v2.mainnet.sng.vultr.icon.community/api/v1/docs/index.html#/Blocks/get_api_v1_blocks_timestamp__timestamp_

This method will not be included in dex because there are no snapshots for pool total.
